xml_path: "g1_description/scene.xml"
simulation_dt: 0.003
control_decimation: 7

head_camera_stream:
  enable: true
  camera_name: "head_rgba_camera"
  host: "0.0.0.0"
  port: 18080
  width: 640
  height: 480
  fps: 20
  jpeg_quality: 80

head_camera_ros2:
  enable: true
  camera_name: "head_rgba_camera"
  width: 640
  height: 480
  fps: 20
  topic_rgb: "/g1/head_camera/rgb"
  topic_rgba: "/g1/head_camera/rgba"
  frame_id: "head_rgba_camera"
  node_name: "g1_head_camera_publisher"
  qos_depth: 5
